import { defineRecipe } from "@chakra-ui/react";
import { EnumColors } from "../../color";
import type { EnumButtonColor } from "./enum/color";
import { EnumButtonSize } from "./enum/size";
import { EnumButtonVariant } from "./enum/vairant";

export const buttonRecipe = defineRecipe({
	base: {
		fontWeight: "bold",
		borderRadius: "8px",
	},
	variants: {
		variant: {
			solid: {},
			subtle: {},
			surface: {},
			outline: {},
			ghost: {},
		},
		size: {
			xs: {
				fontSize: "xs",
				fontWeight: "500",
			},
			sm: {
				fontSize: "sm",
				fontWeight: "500",
			},
			md: {
				fontSize: "md",
				fontWeight: "500",
			},
			lg: {
				fontSize: "lg",
				fontWeight: "500",
			},
			xl: {
				fontSize: "xl",
				fontWeight: "500",
			},
		},
		colorScheme: {
			primary: {},
			secondary: {},
			destructive: {},
			success: {},
			warning: {},
			purple: {},
			orange: {},
			green: {},
			gray: {},
		},
	},
	compoundVariants: [
		// PRIMARY
		{
			variant: "solid",
			colorScheme: "primary",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.primary.DEFAULT,
				borderColor: EnumColors.primary.DEFAULT,
				_hover: { backgroundColor: EnumColors.primary[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "primary",
			css: {
				color: EnumColors.primary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.primary.DEFAULT,
				_hover: { backgroundColor: EnumColors.primary[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "primary",
			css: {
				color: EnumColors.primary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.primary[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "primary",
			css: {
				color: EnumColors.primary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "primary",
			css: {
				color: EnumColors.primary.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.primary[2] },
			},
		},
		// SECONDARY
		{
			variant: "solid",
			colorScheme: "secondary",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.secondary.DEFAULT,
				borderColor: EnumColors.secondary.DEFAULT,
				_hover: { backgroundColor: EnumColors.secondary[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "secondary",
			css: {
				color: EnumColors.secondary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.secondary.DEFAULT,
				_hover: { backgroundColor: EnumColors.secondary[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "secondary",
			css: {
				color: EnumColors.secondary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.secondary[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "secondary",
			css: {
				color: EnumColors.secondary.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "secondary",
			css: {
				color: EnumColors.secondary.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.secondary[2] },
			},
		},
		// DESTRUCTIVE
		{
			variant: "solid",
			colorScheme: "destructive",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.destructive.DEFAULT,
				borderColor: EnumColors.destructive.DEFAULT,
				_hover: { backgroundColor: EnumColors.destructive[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "destructive",
			css: {
				color: EnumColors.destructive.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.destructive.DEFAULT,
				_hover: { backgroundColor: EnumColors.destructive[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "destructive",
			css: {
				color: EnumColors.destructive.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.destructive[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "destructive",
			css: {
				color: EnumColors.destructive.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "destructive",
			css: {
				color: EnumColors.destructive.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.destructive[2] },
			},
		},
		// SUCCESS
		{
			variant: "solid",
			colorScheme: "success",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.success.DEFAULT,
				borderColor: EnumColors.success.DEFAULT,
				_hover: { backgroundColor: EnumColors.success[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "success",
			css: {
				color: EnumColors.success.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.success.DEFAULT,
				_hover: { backgroundColor: EnumColors.success[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "success",
			css: {
				color: EnumColors.success.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.success[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "success",
			css: {
				color: EnumColors.success.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "success",
			css: {
				color: EnumColors.success.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.success[2] },
			},
		},
		// WARNING
		{
			variant: "solid",
			colorScheme: "warning",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.warning.DEFAULT,
				borderColor: EnumColors.warning.DEFAULT,
				_hover: { backgroundColor: EnumColors.warning[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "warning",
			css: {
				color: EnumColors.warning.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.warning.DEFAULT,
				_hover: { backgroundColor: EnumColors.warning[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "warning",
			css: {
				color: EnumColors.warning.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.warning[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "warning",
			css: {
				color: EnumColors.warning.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "warning",
			css: {
				color: EnumColors.warning.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.warning[2] },
			},
		},
		// PURPLE
		{
			variant: "solid",
			colorScheme: "purple",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.purple.DEFAULT,
				borderColor: EnumColors.purple.DEFAULT,
				_hover: { backgroundColor: EnumColors.purple[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "purple",
			css: {
				color: EnumColors.purple.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.purple.DEFAULT,
				_hover: { backgroundColor: EnumColors.purple[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "purple",
			css: {
				color: EnumColors.purple.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.purple[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "purple",
			css: {
				color: EnumColors.purple.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "purple",
			css: {
				color: EnumColors.purple.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.purple[2] },
			},
		},
		// ORANGE
		{
			variant: "solid",
			colorScheme: "orange",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.orange.DEFAULT,
				borderColor: EnumColors.orange.DEFAULT,
				_hover: { backgroundColor: EnumColors.orange[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "orange",
			css: {
				color: EnumColors.orange.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.orange.DEFAULT,
				_hover: { backgroundColor: EnumColors.orange[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "orange",
			css: {
				color: EnumColors.orange.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.orange[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "orange",
			css: {
				color: EnumColors.orange.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "orange",
			css: {
				color: EnumColors.orange.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.orange[2] },
			},
		},
		// GREEN
		{
			variant: "solid",
			colorScheme: "green",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.green.DEFAULT,
				borderColor: EnumColors.green.DEFAULT,
				_hover: { backgroundColor: EnumColors.green[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "green",
			css: {
				color: EnumColors.green.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.green.DEFAULT,
				_hover: { backgroundColor: EnumColors.green[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "green",
			css: {
				color: EnumColors.green.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.green[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "green",
			css: {
				color: EnumColors.green.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "green",
			css: {
				color: EnumColors.green.DEFAULT,
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.green[2] },
			},
		},
		// GRAY
		{
			variant: "solid",
			colorScheme: "gray",
			css: {
				color: EnumColors.white.DEFAULT,
				backgroundColor: EnumColors.gray.DEFAULT,
				borderColor: EnumColors.gray.DEFAULT,
				_hover: { backgroundColor: EnumColors.gray[8] },
			},
		},
		{
			variant: "outline",
			colorScheme: "gray",
			css: {
				color: EnumColors.gray.DEFAULT,
				backgroundColor: "transparent",
				borderColor: EnumColors.gray.DEFAULT,
				_hover: { backgroundColor: EnumColors.gray[2] },
			},
		},
		{
			variant: "ghost",
			colorScheme: "gray",
			css: {
				color: EnumColors.gray.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				_hover: { backgroundColor: EnumColors.gray[2] },
			},
		},
		{
			variant: "subtle",
			colorScheme: "gray",
			css: {
				color: EnumColors.gray.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				padding: "0",
				margin: "0",
				minWidth: "0",
				minHeight: "0",
				borderRadius: "0",
				lineHeight: "normal",
				height: "auto",
				_hover: { textDecoration: "underline", backgroundColor: "transparent" },
			},
		},
		{
			variant: "surface",
			colorScheme: "gray",
			css: {
				color: EnumColors.gray.DEFAULT,
				backgroundColor: "transparent",
				borderColor: "transparent",
				borderRadius: "0px",
				border: "!0px solid transparent",
				width: "100%",
				height: "100%",
				minHeight: "fit-content",
				minWidth: "fit-content",
				boxShadow: "none",
				_hover: { backgroundColor: EnumColors.gray[2] },
			},
		},
	],
	defaultVariants: {
		colorScheme: EnumColors.primary.DEFAULT as EnumButtonColor,
		variant: EnumButtonVariant.SOLID,
		size: EnumButtonSize.M,
	},
});
