export enum EnumButtonColor {
	primary = "primary",
	secondary = "secondary",
	success = "success",
	destructive = "destructive",
	warning = "warning",
	dark = "dark",
	light = "light",
	black = "black",
	white = "white",
	red = "red",
	blue = "blue",
	gray = "gray",
	green = "green",
	orange = "orange",
	purple = "purple",
	pink = "pink",
}
