import { Button, HStack, Text, VStack } from "@chakra-ui/react";
import { EnumButtonColor } from "../theme/componants/button/enum/color";
import { EnumButtonSize } from "../theme/componants/button/enum/size";
import { EnumButtonVariant } from "../theme/componants/button/enum/vairant";

export function ButtonsPage() {
	return (
		<VStack height="100%" width="100%" justify="center">
			<Text color={EnumButtonColor.primary}>Page button</Text>
			<HStack>
				<VStack>
					<Button
						colorScheme={EnumButtonColor.primary}
						size={EnumButtonSize.XS}
					>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.primary} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.primary} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.primary} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.primary}
						size={EnumButtonSize.XL}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.primary}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.primary}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.primary}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.primary}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.primary}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button
						colorScheme={EnumButtonColor.secondary}
						size={EnumButtonSize.XS}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						size={EnumButtonSize.S}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						size={EnumButtonSize.M}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						size={EnumButtonSize.L}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						size={EnumButtonSize.XL}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.secondary}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.secondary}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button
						colorScheme={EnumButtonColor.destructive}
						size={EnumButtonSize.XS}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						size={EnumButtonSize.S}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						size={EnumButtonSize.M}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						size={EnumButtonSize.L}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						size={EnumButtonSize.XL}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.destructive}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.destructive}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button
						colorScheme={EnumButtonColor.success}
						size={EnumButtonSize.XS}
					>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.success} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.success} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.success} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.success}
						size={EnumButtonSize.XL}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.success}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.success}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.success}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.success}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.success}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button
						colorScheme={EnumButtonColor.warning}
						size={EnumButtonSize.XS}
					>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.warning} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.warning} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.warning} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.warning}
						size={EnumButtonSize.XL}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.warning}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.warning}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.warning}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.warning}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.warning}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button colorScheme={EnumButtonColor.purple} size={EnumButtonSize.XS}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.purple} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.purple} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.purple} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.purple} size={EnumButtonSize.XL}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.purple}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.purple}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.purple}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.purple}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.purple}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button colorScheme={EnumButtonColor.orange} size={EnumButtonSize.XS}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.orange} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.orange} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.orange} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.orange} size={EnumButtonSize.XL}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.orange}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.orange}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.orange}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.orange}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.orange}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button colorScheme={EnumButtonColor.green} size={EnumButtonSize.XS}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.green} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.green} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.green} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.green} size={EnumButtonSize.XL}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.green}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.green}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.green}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.green}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.green}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
				<VStack>
					<Button colorScheme={EnumButtonColor.gray} size={EnumButtonSize.XS}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.gray} size={EnumButtonSize.S}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.gray} size={EnumButtonSize.M}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.gray} size={EnumButtonSize.L}>
						solid
					</Button>
					<Button colorScheme={EnumButtonColor.gray} size={EnumButtonSize.XL}>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.gray}
						variant={EnumButtonVariant.SOLID}
					>
						solid
					</Button>
					<Button
						colorScheme={EnumButtonColor.gray}
						variant={EnumButtonVariant.OUTLINE}
					>
						outline
					</Button>
					<Button
						colorScheme={EnumButtonColor.gray}
						variant={EnumButtonVariant.GHOST}
					>
						ghost
					</Button>
					<Button
						colorScheme={EnumButtonColor.gray}
						variant={EnumButtonVariant.SUBTLE}
					>
						subtle
					</Button>
					<VStack width="10rem" color={"transparent"}>
						<Button
							colorScheme={EnumButtonColor.gray}
							variant={EnumButtonVariant.SURFACE}
						>
							surface
						</Button>
					</VStack>
				</VStack>
			</HStack>
		</VStack>
	);
}
